import { useState } from 'react';
import { Download, Copy, CheckCircle, FileJson, BookOpen, Code2, ClipboardList, Rocket } from 'lucide-react';
import { useStore } from '../../store';
import type { Project } from '../../types';

interface Props {
  projectId: string;
  onBack: () => void;
  project: Project;
}

function generateGTMContainer(project: Project): string {
  const selectedElements = project.siteScan
    ? [...(project.siteScan.elements?.highPriority ?? []), ...(project.siteScan.elements?.mediumPriority ?? []), ...(project.siteScan.elements?.lowPriority ?? [])].filter((el) => project.siteScan!.selectedElements.includes(el.id))
    : [];

  const container = {
    exportFormatVersion: 2,
    exportTime: new Date().toISOString(),
    containerVersion: {
      name: `${project.clientName} - Atlas Generated`,
      description: `Auto-generated by Atlas TrackForge on ${new Date().toLocaleDateString()}`,
      container: {
        path: `accounts/000000/containers/000000`,
        accountId: '000000',
        containerId: '000000',
        name: project.clientName,
        publicId: project.deployment?.gtmContainerId || 'GTM-XXXXXXX',
        usageContext: ['WEB'],
      },
      tag: selectedElements.map((el, i) => ({
        accountId: '000000',
        containerId: '000000',
        tagId: String(i + 1),
        name: `GA4 - ${el.suggestedEventName}`,
        type: 'gaawe',
        parameter: [
          { type: 'TEMPLATE', key: 'eventName', value: el.suggestedEventName },
          { type: 'TEMPLATE', key: 'measurementId', value: project.deployment?.ga4PropertyId || '{{GA4 Measurement ID}}' },
        ],
        firingTriggerId: [`trigger_${el.id}`],
        tagFiringOption: 'ONCE_PER_EVENT',
      })),
      trigger: selectedElements.map((el) => ({
        accountId: '000000',
        containerId: '000000',
        triggerId: `trigger_${el.id}`,
        name: `Click - ${el.text}`,
        type: el.type === 'form' ? 'FORM_SUBMISSION' : 'CLICK',
        filter: [{ type: 'MATCHES_CSS_SELECTOR', parameter: [{ type: 'TEMPLATE', key: 'selector', value: el.selector }] }],
      })),
      variable: [
        { accountId: '000000', containerId: '000000', variableId: '1', name: 'GA4 Measurement ID', type: 'c', parameter: [{ type: 'TEMPLATE', key: 'value', value: project.deployment?.ga4PropertyId || 'G-XXXXXXXXXX' }] },
        { accountId: '000000', containerId: '000000', variableId: '2', name: 'GTM Container ID', type: 'c', parameter: [{ type: 'TEMPLATE', key: 'value', value: project.deployment?.gtmContainerId || 'GTM-XXXXXXX' }] },
      ],
    },
  };

  return JSON.stringify(container, null, 2);
}

function generateInstallGuide(project: Project): string {
  const selectedElements = project.siteScan
    ? [...(project.siteScan.elements?.highPriority ?? []), ...(project.siteScan.elements?.mediumPriority ?? []), ...(project.siteScan.elements?.lowPriority ?? [])].filter((el) => project.siteScan!.selectedElements.includes(el.id))
    : [];

  return `# Atlas Tracking Setup - ${project.clientName}
Generated: ${new Date().toLocaleDateString()}
Template: ${project.templateSelection?.templateName ?? 'Custom'}

## Step 1: Import GTM Container
1. Log into Google Tag Manager (tagmanager.google.com)
2. Select your container: ${project.deployment?.gtmContainerId || 'GTM-XXXXXXX'}
3. Go to Admin → Import Container
4. Upload the downloaded GTM_Container.json file
5. Choose "Merge" and "Rename conflicting tags"
6. Click Confirm

## Step 2: Configure Measurement IDs
1. Go to Variables in GTM
2. Update "GA4 Measurement ID" → ${project.deployment?.ga4PropertyId || 'G-XXXXXXXXXX'}
${project.deployment?.metaPixelId ? `3. Update "Meta Pixel ID" → ${project.deployment.metaPixelId}` : ''}

## Step 3: Preview & Test
1. Click "Preview" in GTM
2. Visit your website
3. Test each tracked element:
${selectedElements.map((el) => `   ✓ ${el.text} → ${el.suggestedEventName}`).join('\n')}

## Step 4: Publish
1. Click "Submit" in GTM
2. Add version name: "Atlas Tracking Setup v1"
3. Publish the container

## Tracked Elements (${selectedElements.length} total)
${selectedElements.map((el) => `- [${el.type.toUpperCase()}] ${el.text} → ${el.suggestedEventName}`).join('\n')}
`;
}

function generateVerificationScript(project: Project): string {
  const selectedElements = project.siteScan
    ? [...(project.siteScan.elements?.highPriority ?? []), ...(project.siteScan.elements?.mediumPriority ?? []), ...(project.siteScan.elements?.lowPriority ?? [])].filter((el) => project.siteScan!.selectedElements.includes(el.id))
    : [];

  return `// Atlas TrackForge - Verification Script
// Client: ${project.clientName}
// Generated: ${new Date().toLocaleDateString()}

const verifyAtlasTracking = () => {
  const results = { gtmLoaded: false, ga4Loaded: false, elementsCovered: [], issues: [] };

  // Check GTM
  if (window.google_tag_manager) {
    results.gtmLoaded = true;
    console.log('✓ GTM Loaded:', Object.keys(window.google_tag_manager));
  } else {
    results.issues.push('GTM not detected - check installation');
  }

  // Check GA4
  if (window.gtag || (window.dataLayer && window.dataLayer.some(e => e.event === 'gtm.js'))) {
    results.ga4Loaded = true;
    console.log('✓ GA4 / dataLayer detected');
  } else {
    results.issues.push('GA4 not detected');
  }

  // Check tracked elements
  const trackedSelectors = [
${selectedElements.map((el) => `    { selector: '${el.selector}', event: '${el.suggestedEventName}', label: '${el.text}' }`).join(',\n')}
  ];

  trackedSelectors.forEach(({ selector, event, label }) => {
    const elements = document.querySelectorAll(selector);
    if (elements.length > 0) {
      results.elementsCovered.push({ label, selector, count: elements.length, event });
      console.log('✓ Found:', label, '(' + elements.length + ' instance(s)) →', event);
    } else {
      results.issues.push('Element not found: ' + label + ' (' + selector + ')');
      console.warn('✗ Missing:', label, selector);
    }
  });

  console.log('\\n=== ATLAS VERIFICATION SUMMARY ===');
  console.table(results.elementsCovered);
  if (results.issues.length > 0) {
    console.warn('Issues found:', results.issues);
  } else {
    console.log('✓ All checks passed!');
  }

  return results;
};

verifyAtlasTracking();
`;
}

export default function Phase4Deploy({ projectId, onBack, project }: Props) {
  const { updateProject, addActivity } = useStore();
  const [config, setConfig] = useState({
    gtmContainerId: project.deployment?.gtmContainerId || '',
    ga4PropertyId: project.deployment?.ga4PropertyId || '',
    metaPixelId: project.deployment?.metaPixelId || '',
    linkedInPartnerId: project.deployment?.linkedInPartnerId || '',
  });
  const [copied, setCopied] = useState<string | null>(null);
  const [deployed, setDeployed] = useState(project.status === 'deployed');
  const [activeTab, setActiveTab] = useState<'gtm' | 'guide' | 'verify'>('gtm');

  const projectWithConfig = { ...project, deployment: { ...project.deployment, ...config, verificationStatus: 'pending' as const } };
  const gtmJson = generateGTMContainer(projectWithConfig);
  const installGuide = generateInstallGuide(projectWithConfig);
  const verifyScript = generateVerificationScript(projectWithConfig);

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(null), 2000);
  };

  const handleDownload = (content: string, filename: string, type = 'application/json') => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDeploy = () => {
    updateProject(projectId, {
      status: 'deployed',
      currentPhase: 4,
      deployment: { ...config, verificationStatus: 'pending' },
    });
    addActivity({ type: 'deployed', description: 'Tracking deployed successfully', clientName: project.clientName, timestamp: new Date().toISOString() });
    setDeployed(true);
  };

  const inputStyle = {
    backgroundColor: '#12161E',
    border: '1px solid #1A1E28',
    borderRadius: '8px',
    color: '#E8ECF2',
    padding: '0.5rem 0.75rem',
    width: '100%',
    fontSize: '0.85rem',
    outline: 'none',
    fontFamily: 'Inter, sans-serif',
  };

  const selectedCount = project.siteScan?.selectedElements?.length ?? 0;
  const tabContent = activeTab === 'gtm' ? gtmJson : activeTab === 'guide' ? installGuide : verifyScript;
  const tabFilename = activeTab === 'gtm' ? `${project.clientName}_GTM_Container.json` : activeTab === 'guide' ? `${project.clientName}_Install_Guide.md` : `${project.clientName}_Verify.js`;
  const tabType = activeTab === 'gtm' ? 'application/json' : 'text/plain';

  return (
    <div>
      {deployed && (
        <div style={{ backgroundColor: 'rgba(11,191,170,0.08)', border: '1px solid rgba(11,191,170,0.3)', borderRadius: '8px', padding: '1rem', marginBottom: '1.25rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <CheckCircle size={20} color="#0BBFAA" />
          <div>
            <div style={{ fontWeight: 600, color: '#0BBFAA', fontSize: '0.9rem' }}>Deployment Complete!</div>
            <div style={{ color: '#7A8599', fontSize: '0.8125rem' }}>Tracking setup has been marked as deployed for {project.clientName}.</div>
          </div>
        </div>
      )}

      <div style={{ marginBottom: '1.25rem' }}>
        <h2 style={{ fontFamily: "'Bricolage Grotesque', sans-serif", fontWeight: 700, fontSize: '1.375rem', color: '#E8ECF2', margin: 0, marginBottom: '0.375rem' }}>Deploy Tracking</h2>
        <p style={{ color: '#7A8599', fontSize: '0.875rem', margin: 0 }}>Configure your tracking IDs and download the deployment package.</p>
      </div>

      {/* Config IDs */}
      <div style={{ backgroundColor: '#0D1117', border: '1px solid #1A1E28', borderRadius: '8px', padding: '1.25rem', marginBottom: '1.25rem' }}>
        <h3 style={{ margin: 0, marginBottom: '1rem', fontSize: '0.9375rem', fontWeight: 600, color: '#E8ECF2' }}>Tracking Configuration</h3>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
          {[
            { label: 'GTM Container ID', key: 'gtmContainerId', placeholder: 'GTM-XXXXXXX' },
            { label: 'GA4 Measurement ID', key: 'ga4PropertyId', placeholder: 'G-XXXXXXXXXX' },
            { label: 'Meta Pixel ID (optional)', key: 'metaPixelId', placeholder: '123456789012345' },
            { label: 'LinkedIn Partner ID (optional)', key: 'linkedInPartnerId', placeholder: '1234567' },
          ].map(({ label, key, placeholder }) => (
            <div key={key}>
              <label style={{ display: 'block', color: '#7A8599', fontSize: '0.8rem', fontWeight: 500, marginBottom: '0.3rem' }}>{label}</label>
              <input
                value={config[key as keyof typeof config]}
                onChange={(e) => setConfig({ ...config, [key]: e.target.value })}
                placeholder={placeholder}
                style={inputStyle}
                onFocus={(e) => (e.target.style.borderColor = '#0BBFAA')}
                onBlur={(e) => (e.target.style.borderColor = '#1A1E28')}
              />
            </div>
          ))}
        </div>
      </div>

      {/* Summary */}
      <div style={{ backgroundColor: '#0D1117', border: '1px solid #1A1E28', borderRadius: '8px', padding: '1.25rem', marginBottom: '1.25rem' }}>
        <h3 style={{ margin: 0, marginBottom: '0.875rem', fontSize: '0.9375rem', fontWeight: 600, color: '#E8ECF2' }}>Deployment Summary</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
          <div style={{ backgroundColor: '#12161E', borderRadius: '8px', padding: '0.875rem', textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: 700, color: '#0BBFAA', fontFamily: "'Bricolage Grotesque', sans-serif" }}>{selectedCount}</div>
            <div style={{ fontSize: '0.75rem', color: '#7A8599', marginTop: '0.25rem' }}>Elements Tracked</div>
          </div>
          <div style={{ backgroundColor: '#12161E', borderRadius: '8px', padding: '0.875rem', textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: 700, color: '#818cf8', fontFamily: "'Bricolage Grotesque', sans-serif" }}>{selectedCount}</div>
            <div style={{ fontSize: '0.75rem', color: '#7A8599', marginTop: '0.25rem' }}>GTM Triggers</div>
          </div>
          <div style={{ backgroundColor: '#12161E', borderRadius: '8px', padding: '0.875rem', textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: 700, color: '#fb923c', fontFamily: "'Bricolage Grotesque', sans-serif" }}>{selectedCount}</div>
            <div style={{ fontSize: '0.75rem', color: '#7A8599', marginTop: '0.25rem' }}>GA4 Events</div>
          </div>
        </div>
      </div>

      {/* Code Preview Tabs */}
      <div style={{ backgroundColor: '#0D1117', border: '1px solid #1A1E28', borderRadius: '8px', marginBottom: '1.25rem', overflow: 'hidden' }}>
        <div style={{ display: 'flex', borderBottom: '1px solid #1A1E28' }}>
          {[
            { key: 'gtm', icon: <FileJson size={14} />, label: 'GTM Container JSON' },
            { key: 'guide', icon: <BookOpen size={14} />, label: 'Install Guide' },
            { key: 'verify', icon: <Code2 size={14} />, label: 'Verify Script' },
          ].map(({ key, icon, label }) => (
            <button key={key} onClick={() => setActiveTab(key as 'gtm' | 'guide' | 'verify')} style={{ flex: 1, padding: '0.75rem', background: activeTab === key ? '#12161E' : 'transparent', border: 'none', borderBottom: activeTab === key ? '2px solid #0BBFAA' : '2px solid transparent', color: activeTab === key ? '#E8ECF2' : '#7A8599', fontSize: '0.8125rem', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.375rem', fontWeight: activeTab === key ? 500 : 400 }}>
              {icon} {label}
            </button>
          ))}
        </div>
        <div style={{ position: 'relative' }}>
          <div style={{ display: 'flex', gap: '0.5rem', padding: '0.625rem 0.875rem', borderBottom: '1px solid #1A1E28', justifyContent: 'flex-end' }}>
            <button onClick={() => handleCopy(tabContent, activeTab)} style={{ background: 'none', border: '1px solid #1A1E28', borderRadius: '6px', color: copied === activeTab ? '#0BBFAA' : '#7A8599', padding: '0.25rem 0.625rem', fontSize: '0.75rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
              {copied === activeTab ? <CheckCircle size={12} /> : <Copy size={12} />}
              {copied === activeTab ? 'Copied!' : 'Copy'}
            </button>
            <button onClick={() => handleDownload(tabContent, tabFilename, tabType)} style={{ background: 'none', border: '1px solid #1A1E28', borderRadius: '6px', color: '#7A8599', padding: '0.25rem 0.625rem', fontSize: '0.75rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.375rem' }}>
              <Download size={12} /> Download
            </button>
          </div>
          <pre style={{ backgroundColor: '#080B12', padding: '1rem', fontFamily: 'JetBrains Mono, monospace', fontSize: '0.75rem', color: activeTab === 'gtm' ? '#0BBFAA' : activeTab === 'guide' ? '#E8ECF2' : '#818cf8', margin: 0, overflowX: 'auto', maxHeight: '300px', lineHeight: 1.6 }}>
            {tabContent}
          </pre>
        </div>
      </div>

      {/* Checklist */}
      <div style={{ backgroundColor: '#0D1117', border: '1px solid #1A1E28', borderRadius: '8px', padding: '1.25rem', marginBottom: '1.25rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.875rem' }}>
          <ClipboardList size={16} color="#0BBFAA" />
          <h3 style={{ margin: 0, fontSize: '0.9375rem', fontWeight: 600, color: '#E8ECF2' }}>Pre-Launch Checklist</h3>
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {[
            'GTM container downloaded',
            'GTM container imported and merged',
            'All measurement IDs configured',
            'GTM Preview mode tested',
            'All events verified in GA4 DebugView',
            'Container published',
          ].map((item) => (
            <label key={item} style={{ display: 'flex', alignItems: 'center', gap: '0.625rem', color: '#E8ECF2', fontSize: '0.875rem', cursor: 'pointer' }}>
              <input type="checkbox" style={{ accentColor: '#0BBFAA', width: '15px', height: '15px' }} />
              {item}
            </label>
          ))}
        </div>
      </div>

      {/* Actions */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={onBack} style={{ background: 'transparent', border: '1px solid #1A1E28', borderRadius: '8px', color: '#E8ECF2', padding: '0.625rem 1.25rem', fontSize: '0.875rem', cursor: 'pointer' }}>Back</button>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button onClick={() => handleDownload(gtmJson, `${project.clientName}_GTM_Container.json`)} style={{ background: 'transparent', border: '1px solid #1A1E28', borderRadius: '8px', color: '#E8ECF2', padding: '0.625rem 1.25rem', fontSize: '0.875rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Download size={15} /> Download All
          </button>
          <button
            onClick={handleDeploy}
            disabled={deployed}
            style={{ background: deployed ? 'rgba(11,191,170,0.15)' : 'linear-gradient(135deg, #0BBFAA, #099d8b)', color: deployed ? '#0BBFAA' : '#080B12', fontWeight: 600, fontSize: '0.875rem', padding: '0.625rem 1.5rem', borderRadius: '8px', border: deployed ? '1px solid rgba(11,191,170,0.3)' : 'none', cursor: deployed ? 'default' : 'pointer', display: 'flex', alignItems: 'center', gap: '0.5rem' }}
          >
            {deployed ? <><CheckCircle size={15} /> Deployed</> : <><Rocket size={15} /> Mark as Deployed</>}
          </button>
        </div>
      </div>
    </div>
  );
}
