import { Router, Request, Response } from 'express';

const router = Router();

router.post('/gtm-container', (req: Request, res: Response) => {
  const { project, selectedElements, clientConfig } = req.body;

  if (!selectedElements || !clientConfig) {
    return res.status(400).json({ error: 'selectedElements and clientConfig are required' });
  }

  const container = {
    exportFormatVersion: 2,
    exportTime: new Date().toISOString(),
    containerVersion: {
      name: `${clientConfig.clientName || 'Client'} - Atlas Generated`,
      description: `Auto-generated by Atlas TrackForge`,
      container: {
        name: clientConfig.clientName || 'Client',
        publicId: clientConfig.gtmContainerId || 'GTM-XXXXXXX',
        usageContext: ['WEB'],
      },
      tag: selectedElements.map((el: any, i: number) => ({
        tagId: String(i + 1),
        name: `GA4 - ${el.suggestedEventName}`,
        type: 'gaawe',
        parameter: [
          { type: 'TEMPLATE', key: 'eventName', value: el.suggestedEventName },
          { type: 'TEMPLATE', key: 'measurementId', value: clientConfig.ga4PropertyId || '{{GA4 Measurement ID}}' },
        ],
        firingTriggerId: [`trigger_${el.id}`],
      })),
      trigger: selectedElements.map((el: any) => ({
        triggerId: `trigger_${el.id}`,
        name: `Click - ${el.text}`,
        type: el.type === 'form' ? 'FORM_SUBMISSION' : 'CLICK',
        filter: [{ type: 'MATCHES_CSS_SELECTOR', parameter: [{ type: 'TEMPLATE', key: 'selector', value: el.selector }] }],
      })),
      variable: [
        { name: 'GA4 Measurement ID', type: 'c', parameter: [{ type: 'TEMPLATE', key: 'value', value: clientConfig.ga4PropertyId || 'G-XXXXXXXXXX' }] },
      ],
    },
  };

  res.json({ success: true, container });
});

export default router;
